### ISSUE TITLE
Implement endless scrolling

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Vision#11]
Unfinished code for implementation:

<details><summary>JS</summary>

```js
const mainElement = document.querySelector('main');
const getLastPostElement = () => mainElement.querySelector('article:last-of-type');

let nextPageUrl = document.getElementById('next-link')?.href;

const callback = (entries, observer) => {
  if ([...entries].every(({ isIntersecting }) => !isIntersecting)) return;
  observer.disconnect();
  mainElement.setAttribute('aria-busy', 'true');

  fetch(nextPageUrl)
    .then(response => response.text())
    .then(responseText => {
      const responseDocument = (new DOMParser()).parseFromString(responseText, 'text/html');
      const articles = [...responseDocument.querySelectorAll('main > article')];
      const postIds = articles.map(({ id }) => id);

      mainElement.append(...articles);
      Tumblr.LikeButton.get_status_by_post_ids(postIds);
      history.pushState({}, document.title, nextPageUrl);

      mainElement.setAttribute('aria-busy', 'false');
      nextPageUrl = responseDocument.getElementById('next-link')?.href;
      if (nextPageUrl) observer.observe(getLastPostElement());
    })
    .catch(exception => {
      console.error(exception);
      mainElement.removeAttribute('aria-busy');
    });
};

if (nextPageUrl && mainElement.getAttribute('role') === 'feed') {
  const observer = new IntersectionObserver(callback);
  mainElement.setAttribute('aria-busy', 'false');
  observer.observe(getLastPostElement());
}
```
</details>

<details><summary>CSS</summary>

```css
main[role="feed"] #pagination {
    display: none;
}

main[aria-busy="true"]::after {
    display: block;
    margin-top: var(--post-margin);
    
    color: rgba(var(--title), 0.65);
    text-align: center;
}
```
```css
            main[aria-busy="true"]::after {
                content: "{lang:Loading}";
            }
```
</details>

<details><summary>HTML</summary>

```html
<main {block:Pagination}role="feed"{/block:Pagination}>
```
</details>
