### ISSUE TITLE
Empty tip `.answer_content` creates unused vertical height

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Vision#19]
![image](https://user-images.githubusercontent.com/28949509/154806363-b2781d65-c9b9-4764-a58c-d4590faf405b.png)

Fix:
```css
li.note .answer_content:empty {
  display: none;
}
```
