### ISSUE TITLE
always use 16:9 ratio to display header image

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Vision#21]
WIP code

```css
#header.stretch {
  height: calc(var(--aside-width) / 2);
}

@media (max-width: 900px) {
  :root {
    --aside-width: min(100vw, var(--post-width));
  }

  #header.stretch {
    height: calc(var(--aside-width * (9 / 16));
  }
}
```
