### ISSUE TITLE
add styles to NPF audio metadata

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Vision#24]
```css
.tmblr-full > .audio-caption {
  background-color: rgb(var(--accent));
  color: rgb(var(--background));
}
```

Current | Desired
-|-
![Screen Shot 2023-07-22 at 13 25 13](https://github.com/AprilSylph/Vision/assets/28949509/dddd5d11-f377-4035-945a-833651bc2238) | ![Screen Shot 2023-07-22 at 13 25 57](https://github.com/AprilSylph/Vision/assets/28949509/07b6e7d6-99b6-43f5-b924-03a40cecfa13)
