### ISSUE TITLE
Anonymous submissions appear incorrectly in notes

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Vision#6]
example: <https://shitpeoplesayintf2.tumblr.com/post/656360802504310784#notes>

https://github.com/AprilSylph/Vision/blob/e450ec5a5c5de41b1d138eda92b366cebd38ada5/Vision%20Core.css#L1037
```diff
- li.note .avatar_frame {
+ li.note .avatar_frame,
+ li.note > .avatar {
```
```css
li.note > .avatar {
  margin-right: calc(1ch - 0.25rem);
}
```
