### ISSUE TITLE
Post attribution can overflow from parent

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Vision#8]
Particularly an issue on the "Recently Liked" section where space is at a premium.

Could be fixed with:
```css
.post-attribution {
    min-width: 0;
    flex: 1;
    overflow: hidden;
}
```

Also, setting `.post-attribution { flex-direction: column; }` may be unnecessary (`flex-wrap: wrap;` should suffice) but further testing will be needed.

---

Related notes:
- post actions shouldn't be rendered on Recently Liked
- `.post-attribution` shouldn't really have `margin-right` at all (instead, put left margin on post actions)
